security:
    password_hashers:
        App\Entity\Login\Usuarios:
            algorithm: auto

    providers:
        usuarios_provider:
            entity:
                class: App\Entity\Login\Usuarios
                property: correo

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: /logout                
        login:
            pattern: ^/api/login
            stateless: true
            provider: usuarios_provider
            json_login:
                check_path: /api/login
                username_path: _username
                password_path: _password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                # failure_handler se puede eliminar
                # no se requiere entry_point

        register:
            pattern: ^/api/register
            stateless: true
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: usuarios_provider
            jwt: ~
            # NO entry_point


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10


